version: '3.9'

services:
  app:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=clustering
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: pg-database
    environment:
      POSTGRES_DB: clustering
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
